"""Low-level helpers shared across great-docs modules, free of import side effects"""

from __future__ import annotations

import re
from collections.abc import Sequence
from pathlib import Path

_SEEALSO_RE = re.compile(
    r"^[^\S\r\n]*%seealso[^\S\r\n]+(.+?)[^\S\r\n]*$",
    re.MULTILINE,
)
_FENCE_RE = re.compile(r"^[ \t]*(?P<fence>`{3,}|~{3,})(?P<info>.*)$")


def fenced_lines(text: str) -> tuple[list[str], list[bool]]:
    """
    Split source text and identify lines contained by Markdown code fences

    Parameters
    ----------
    text
        Source text to classify.

    Returns
    -------
    Source lines and a mask marking opening fences, fenced content, and
    closing fences.
    """
    lines = text.splitlines()
    if "```" not in text and "~~~" not in text:
        return lines, [False] * len(lines)

    fenced: list[bool] = []
    fence_char = ""
    fence_length = 0

    for line in lines:
        may_be_fence = "`" in line or "~" in line
        match = _FENCE_RE.match(line) if may_be_fence else None
        if not fence_char:
            if match is None:
                fenced.append(False)
                continue
            fence = match.group("fence")
            if fence.startswith("`") and "`" in match.group("info"):
                fenced.append(False)
                continue
            fence_char = fence[0]
            fence_length = len(fence)
            fenced.append(True)
            continue

        fenced.append(True)
        stripped = line.lstrip()
        closing_length = len(stripped) - len(stripped.lstrip(fence_char))
        if closing_length >= fence_length and not stripped[closing_length:].strip():
            fence_char = ""
            fence_length = 0

    return lines, fenced


def parse_seealso(docstring: str) -> list[tuple[str, str]]:
    """
    Parse the `%seealso` directive of a docstring into `(name, description)` pairs

    The directive is a comma-separated list of entries, each an optionally
    `name : description` pair. Undescribed entries get an empty description;
    entries with a blank name are dropped. Returns an empty list when no
    `%seealso` directive is present.
    """
    entries: list[tuple[str, str]] = []
    for match in _SEEALSO_RE.finditer(docstring):
        for entry in match.group(1).split(","):
            name, _, desc = entry.partition(":")
            name = name.strip()
            if name:
                entries.append((name, desc.strip()))
    return entries


QUARTO_YML_HEADER = (
    "# Generated by Great Docs - Do not modify this file by hand.\n"
    "# Configure settings in great-docs.yml instead.\n\n"
)


def is_great_docs_build_dir(path: Path) -> bool:
    """
    Identify a Great Docs-generated Quarto project directory

    The directory must contain a readable UTF-8 `_quarto.yml` that begins with
    the complete generated-file header. The exact match prevents build cleanup
    from treating user directories as generated output.

    Parameters
    ----------
    path
        Directory to inspect.

    Returns
    -------
    Whether the directory contains a Great Docs-generated `_quarto.yml`.
    """
    try:
        with (path / "_quarto.yml").open(encoding="utf-8") as quarto_yml:
            header = quarto_yml.read(len(QUARTO_YML_HEADER))
    except (OSError, UnicodeDecodeError):
        return False
    return header == QUARTO_YML_HEADER


def is_in_great_docs_build_dir(parts: Sequence[str], project_root: Path) -> bool:
    """
    Identify a project-relative path within Great Docs build output

    Every path below the root `great-docs/` directory belongs to the current
    build. A path below a root `great-docs-<tag>/` directory belongs to a
    historical build only when that directory is not a symlink and contains
    the complete generated-file header. Similar names elsewhere remain source
    paths.

    Parameters
    ----------
    parts
        Path components relative to `project_root`.
    project_root
        Project root used to inspect historical build directories.

    Returns
    -------
    Whether the path belongs to current or historical build output.
    """
    if not parts:
        return False

    name = parts[0]
    if name == "great-docs":
        return True
    if not name.startswith("great-docs-"):
        return False

    candidate = project_root / name
    return candidate.is_dir() and not candidate.is_symlink() and is_great_docs_build_dir(candidate)
