"""Low-level helpers shared across great-docs modules, free of import side effects"""

from __future__ import annotations

import re
from collections.abc import Sequence
from pathlib import Path

_SEEALSO_RE = re.compile(
    r"^[^\S\r\n]*%seealso[^\S\r\n]+(.+?)[^\S\r\n]*$",
    re.MULTILINE,
)
_FENCE_RE = re.compile(r"^[ \t]*(?P<fence>`{3,}|~{3,})(?P<info>.*)$")


def fenced_lines(text: str) -> tuple[list[str], list[bool]]:
    """
    Split source text and identify lines contained by Markdown code fences

    Parameters
    ----------
    text
        Source text to classify.

    Returns
    -------
    Source lines and a mask marking opening fences, fenced content, and
    closing fences.
    """
    lines = text.splitlines()
    if "```" not in text and "~~~" not in text:
        return lines, [False] * len(lines)

    fenced: list[bool] = []
    fence_char = ""
    fence_length = 0

    for line in lines:
        may_be_fence = "`" in line or "~" in line
        match = _FENCE_RE.match(line) if may_be_fence else None
        if not fence_char:
            if match is None:
                fenced.append(False)
                continue
            fence = match.group("fence")
            if fence.startswith("`") and "`" in match.group("info"):
                fenced.append(False)
                continue
            fence_char = fence[0]
            fence_length = len(fence)
            fenced.append(True)
            continue

        fenced.append(True)
        stripped = line.lstrip()
        closing_length = len(stripped) - len(stripped.lstrip(fence_char))
        if closing_length >= fence_length and not stripped[closing_length:].strip():
            fence_char = ""
            fence_length = 0

    return lines, fenced


def parse_seealso(docstring: str) -> list[tuple[str, str]]:
    """
    Parse the `%seealso` directive of a docstring into `(name, description)` pairs

    The directive is a comma-separated list of entries, each an optionally
    `name : description` pair. Undescribed entries get an empty description;
    entries with a blank name are dropped. Returns an empty list when no
    `%seealso` directive is present.
    """
    entries: list[tuple[str, str]] = []
    for match in _SEEALSO_RE.finditer(docstring):
        for entry in match.group(1).split(","):
            name, _, desc = entry.partition(":")
            name = name.strip()
            if name:
                entries.append((name, desc.strip()))
    return entries


QUARTO_YML_HEADER = (
    "# Generated by Great Docs - Do not modify this file by hand.\n"
    "# Configure settings in great-docs.yml instead.\n\n"
)

_QUARTO_YML_MARKER = "Generated by Great Docs"


def is_great_docs_build_dir(path: Path) -> bool:
    """
    Check whether a directory contains a Great Docs-generated Quarto project

    A directory qualifies only when its `_quarto.yml` contains the Great Docs
    marker. Missing, unreadable, and unmarked files return `False`, which keeps
    callers from deleting directories they cannot identify as build output.

    Parameters
    ----------
    path
        Directory to inspect.

    Returns
    -------
    Whether the directory contains a Great Docs-generated `_quarto.yml`.
    """
    try:
        head = (path / "_quarto.yml").read_text(encoding="utf-8")[:200]
    except (OSError, UnicodeDecodeError):
        return False
    return _QUARTO_YML_MARKER in head


def is_in_great_docs_build_dir(parts: Sequence[str]) -> bool:
    """
    Check whether a project-relative path is inside Great Docs build output

    Treat a root `great-docs/` or `great-docs-<tag>/` component as temporary
    build output. Check only the first component so nested project directories,
    such as `docs/great-docs-examples/`, remain source content.

    Parameters
    ----------
    parts
        Components of a path relative to the project root.

    Returns
    -------
    Whether the first component names a Great Docs build directory.
    """
    return bool(parts) and (parts[0] == "great-docs" or parts[0].startswith("great-docs-"))
